### ISSUE TITLE
Minor release issue

### ISSUE THREAD

**Issue by dsebastien** [mraible/infoq-mini-book#42]
Hello Matt, 

In my repo, I've integrated the github publish action, but encountered a problem with my release workflow.
With it, I simply use `git tag x.y.z` then `git push --tags`. Unfortunately, when doing that, the upload-assets action fails with a pretty hard to understand error: "Not Found".

It seems to be a known issue: https://github.com/alexellis/upload-assets/issues/2

To fix this, I've adapted the publish.yml file as follows in my repo:

```
      - name: Rename files
       ...
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          body: |
            w00t, almost there!
      - name: Upload release assets
        uses: alexellis/upload-assets@0.2.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["build/{*.pdf,*.epub,*.zip}"]'
```

As you can see, it's pretty much the same as before, apart from the fact that I've added a "Create Release" job, which creates a Github release along the way. Thanks to that, the release is created before the upload-assets action executes and it then works as expected.

I haven't created a PR, because I don't know if this behavior is intended for everyone; but I thought that it might be of use to others.
